name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker
      run: docker login -u brandonarbour -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: |
        pwd
        ls -lh
        docker build './Web App' --file Dockerfile -t brandonarbour/capstone-web:latest
    - name: Push the Docker image
      run: docker push brandonarbour/capstone-web:latest