name: Deploy to production

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull latest dev image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/dev-capstone-web:latest

    - name: Tag image for prod repo
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/dev-capstone-web:latest ${{ secrets.DOCKER_USERNAME }}/capstone-web:latest
        docker tag ${{ secrets.DOCKER_USERNAME }}/capstone-web:latest ${{ secrets.DOCKER_USERNAME }}/capstone-web:${GITHUB_SHA::7}
        
    - name: Run vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with: 
        image-ref: '${{ secrets.DOCKER_USERNAME }}/capstone-web:latest'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/capstone-web --all-tags

    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ vars.AWS_REGION }}
        role-session-name: GitHub-OIDC-Terraform
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.5
    
    - name: Terraform Init
      id: init
      env:
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_BUCKET_PROD_TFSTATES: ${{ secrets.AWS_BUCKET_PROD_TFSTATES }}
      run: |
        cd ./Terraform/Prod
        terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_PROD_TFSTATES}" -backend-config="region=${AWS_REGION}"

    - name: Terraform Validate
      id: validate
      run: |
        cd ./Terraform/Prod
        terraform validate
    
    - name: Terraform Apply
      run: |
        cd ./Terraform/Prod
        terraform apply -auto-approve -var "prod_cidr_ipv4=${{ secrets.PROD_CIDR_IPV4 }}" -var "prod_image_name=${{ secrets.DOCKER_USERNAME }}/capstone-web:${GITHUB_SHA::7}"