name: Scan repo

on:
  workflow_dispatch:
  schedule:
    - cron: '20 11 * * 2,4'

jobs:
  scan-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@0.28.0

      - name: Run Trivy secret scanner in repo mode
        run: trivy fs --security-checks secret .